### ISSUE TITLE
unable to build on WSL:ubuntu-20.04

### ISSUE THREAD

**Issue by jcherrabi** [WebThingsIO/crateway#49]
Hello guys,
trying to test the rust edition, i cloned it run the ./setup.sh which complete fine since it conly clones the gateway and install the dependencies, but running `cargo run` give an error when it tries to build the crateway at the very last step, complaining about `note: /usr/bin/ld: cannot find -lsqlite3`

muy guess was something to do with the cross compilation, so i tried to add the proper flag for my machine in `~/.cargo/config.toml` as follow: 
`# Specify which linker to use for this target`
`[target.x86_64-unknown-linux-gnu]`
`linker = "x86_64-linux-gnu-gcc" `
 but i get the error.
Can you please tell me which architecture i should target? or how to successfully build this on Windows 10 ruing WSL:Ubuntu-20.04

btw may i recommend adding the following to the readme: install the nightly build of rustup using the following command: `rustup default nightly` and if one needs to go back to stable version they can run `rustup default stable`

looking forward to testing the rust edition.
cheers,

**Comment by jcherrabi** [comment]
hello guys,
i was able to fix the issue by using the following steps:
1. `sudo apt-get install libsqlite3-dev`
2. `sudo apt install luarocks`
3. `sudo luarocks install lsqlite3`

now it works

**Comment by bewee** [comment]
Hello @jcherrabi,

Thank you for submitting your issue and solution! I created a PR for editing the README to include the installation of necessary dependencies: #50.
I assume these packages are pre-installed on most Linux distros. For some reason they were already installed on my WSL too, I suppose I must have installed them already some other time 😅 

Cheers!
